### ISSUE TITLE
Documentação_PagOpenPix

### ISSUE THREAD

**Issue by AsaphF** [Open-Pix/developers#174]
[openPix_md.md](https://github.com/Open-Pix/developers/files/10270180/openPix_md.md)

**Comment by daniloab** [comment]
How can we make this readable?

**Comment by AsaphF** [comment]
Do you prefeer that i send on other type of document?

**Comment by AsaphF** [comment]
Criei um Notion, caso ajude:

https://www.notion.so/OpenPix-Page-9d961f35c3014a36a5c1048fd727d4a1

**Comment by AsaphF** [comment]
---
id: openpix-doc
title: Documentação-das-página-e-sugestões-de-atualizações
sidebar_label: Docs
tags:
- Introdução
- #Página-Principal
- comecando
---

# Introdução:

 Esse arquivo está dividido em duas partes: Referência e Sugestões. A referência terá o propósito de auxiliar a equipe
 quando for necessário fazer atualizações, como também guiar novos desenvolvedores quando estiverem no processo de familiarização
 do projeto; as sugestões terão o propósito de ao analisar a página, apontar meios de melhorá-la tendo em vista o usuário final,
 será avaliado assim,  o design, a tipografia, marketing de conteúdo, como também funcionalidade e responsividade da página. 
 
 obs: A refência será divivida seção por seção onde a equipe poderá retirar e adicionar elementos; essa servirá apenas como a estrutura.
 
 # REFERÊNCIA:
 
 ## 1. Página Principal:
 
  a. Header:
     - Conteúdo =>
       . Propósito: // A preencher 
       . Qualidade: // A preencher 
     - Design => 
       . logo: // A preencher 
       . color: white
       . background-color: // A preencher 
       . media-queries: // A preencher
       . Tamanho do elementos: // A preencher
    - Tipografia
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       . text-decoration: // A preencher 
   
   a.1. Menu Mobile:
     - Design => 
       . color: white
       . background-color: // A preencher 
       . Tipo:
  
  b. Main:
  
   b.1. Seção Plataforma:
      - Conteúdo =>
       . Propósito: // A preencher 
       . Qualidade: // A preencher 
      - Design => 
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . media-queries: // A preencher 
       . Tamanho do elementos: // A preencher
    - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
   
   b.2. Seção Plugins:
      - Conteúdo =>
       . Propósito:
       . Qualidade:
      - Design => 
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . imagem: // A preencher 
       . media-queries: // A preencher 
       . Tamanho do elementos: // A preencher
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       . text-decoration:  // A preencher 
       
   b.3. Seção Conta-Cliente:
      - Conteúdo =>
       . Propósito:
       . Qualidade:
      - Design => 
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . imagem: // A preencher 
       . media-queries: // A preencher
       . Tamanho do elementos: // A preencher
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
       
   b.4. Seção módulos, Integrações e diferenciais:
      - Conteúdo =>
       . Propósito:
       . Qualidade:
      - Design => 
       . logos: // A preencher   
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . bordas: // A preencher
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
   b.4. Seção de oferta:
      - Conteúdo =>
       . Propósito:
       . Qualidade:
      - Design =>
       . color: white
       . background-color: // A preencher 
       . bordas: // A preencher
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  b. Footer:
      - Conteúdo =>
       . Propósito:
       . Qualidade:
      - Design =>
       . logo: / A preencher 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  1.1 Análise e sugestões:
  
  a. Análise
  
   - Funcionalidade: Não encontrei nenhum bug que impedisse a página de funcionar como deveria.
   - Responsividade:
   Na versão desktop apartir de 600px para baixo os elementos começam a se misturar. Na versão mobile, a uma melhor organização dos componentes porém,
   percebir uma falta de espaçamento entre os textos e as imagens como também entre os componentes.
   Pedi para três pessoas propensas a serem usuários a olhar o site para terem sua opnião e todas comentaram sobre o layout da página como sendo confuso de entender.
   
  b. Sugestões:
  
   - Idioma: Sugiro haver uma funcionalidade que altera o conteúdo só para o idioma selecionado, tendo em vista que a Woovi também possui clientes internacionais.
  
   - Layout: O layout mobile acredito que é o único que pdoeria ser alterado, me refiro mais ao "font-size" dos elementos e do "gap" entre eles.
     Me refiro  sobre as seções antes da lista de módulos.
  
   
   - Conteúdo(Mobile e desktop): 
   
       A apresentação do site em si, está boa. É possível distinguir entre os componenetes. O problema que vejo está na parte de conteúdo e da interação do cliente com ele.
     O público alvo pode ser dividido em dois: Os que não possuem plataforma de e-Commerce e os que possuem, então o site precisa ter um conteúdo atraente para os dois
     tipos de públicos e isso precisa estar bem transparente na página.
     
     * Header: O item do "nav" poderia ficar mais claro e alterar de "Falar com Vendas" para "Falar com o setor de vendas" ou algo parecido.
   
     * Seção da Plataforma de gestão: Ótimo e funcional título, é entendível e o uso da linguagem é boa. Porém eu, como usuário, não tenho acesso a mais infomarções
     sobre o que é essa plataforma em detalhes, o que ela oferece, o que eu posso ganhar com ela, os benefícios e o uso em si. Então a minha sugestão para esse
     componente seria duas: Ou depos do título houvesse uma lista, ou parágrafo com um conteúdo de marketing da plataforma e aí depois vêm o botão de acesso ao formulário,
     Ou, mudar o nome do botão de "Começar a usar Pix na sua Empresa" para "Saiba mais" ou algo do tipo, e apartir que o botão fosse selecionado, o próprio componente mudaria o
     conteúdo para um  que vendesse a plataforma(parecido como a seção plugin faz), e aí sim o botão "Começar a usar Pix na sua Empresa" estaria presente para ser direcionado para o formulário.
    
     * Seção Plugins:  A únicas sugestões que teria seria adcionar um título mais interativo e atrativo ao cliente, algo como: "Você possui já uma plataforma de e-commerce, venha conhecer mais sobre os nossos plugins..." 
     ou algo nesse sentido, o ponto que eu quero destacar é que ao mudar a abordagem, a seção direciona para qual público ela tem o enfoque, tazendo assim uma maior clareza entre os outros componentes.
     Também sugiro a mesma abordagem na parte da apresentação dos plugins(após o cliente apertar o botão).
     
     * Seção Conta-Cliente: Essa seção faz muito bem a apresentação do conteúdo no título e subtítulo, só sugiro adicionar um pouco, talvez em uma lista, que apareceria após apertar um botão de "saiba mais",
     contendo os benefícios que a plataforma trás e como amplia as funcionalidades da conta.
     
     * Seção módulos, Integrações e diferenciais: Para esse seção eu sugiro apenas uma mudança na linguagem utilizada, sair de uma linguagem técnica para uma linguagem de venda de marketing. E deixar em apenas um idioma.
 
     * Seção de oferta: Nada a declarar.
     
     * Footer: Caso alteração e títulos também alterar na corresponde parte no footer.
     
 
## 2. Página Módulos:
 
  a. Main:
  
   a.1. Título e Sub-título:
      - Design => 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
    - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
   
  a.2. Seção módulos:
      - Design => 
       . logos: // A preencher   
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . bordas: // A preencher
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  b. Footer:
      - Design =>
       . logo: / A preencher 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  2.1 Análise e sugestões:
     
   a. Análise: 
    - Funcionalidade: Não encontrei nenhum bug que impedisse a página de funcionar como deveria.
    - Responsividade: Nada a declarar.
     
   b. Sugestões: 
   
    - Módulos: Para esse seção eu sugiro apenas uma mudança na linguagem utilizada, sair de uma linguagem técnica para uma linguagem de venda de marketing. E deixar em apenas um idioma.
      Ao selecionar o módulo: A explicação do que cada módulo faz está muito boa, não acredito que precise de alteração, só levar em consideração os sugestões acima.
     
      
## 3. Página de Planos: 
   a. Main:
  
    a.1. Título e Sub-título:
      - Design => 
       . color: white
       . Tamanho do elementos: // A preencher
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
  
  a.2. Cards dos Planos:
     - Design => 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . Box-shadow: // A preencher 
       . logo_imagens: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  a.3. Seção módulos:
      - Design => 
       . logos: // A preencher   
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . bordas: // A preencher
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  b. Footer:
      - Design =>
       . logo: / A preencher 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  3.1 Análise e sugestões:
     
   a. Análise: 
    - Funcionalidade: Não encontrei nenhum bug que impedisse a página de funcionar como deveria.
    - Responsividade: Nada a declarar.
     
   b. Sugestões: 

    - Módulos: Para esse seção eu sugiro apenas uma mudança na linguagem utilizada, sair de uma linguagem técnica para uma linguagem de venda de marketing. E deixar em apenas um idioma.
      Ao selecionar o módulo: A explicação do que cada módulo faz está muito boa, não acredito que precise de alteração, só levar em consideração os sugestões acima.
      
##  Página de "Falar com vendas":  
   a. Main:
  
    a.1. Forms:
      - Design => 
       . color: white
       . Tamanho do elementos: // A preencher
 
       
    b. Footer:
      - Design =>
       . logo: / A preencher 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  4.1 Análise e sugestões:
     
   a. Análise: 
    - Funcionalidade: Não encontrei nenhum bug que impedisse a página de funcionar como deveria.
    - Responsividade: Nada a declarar.
     
   b. Sugestões: 

    - Apenas sugiro alterar o nome da página para "Falar com Setor de Vendas" ou algo nesse sentido.
     
## 5. Página Conta Virtual:
 
  a. Título e Sub-Título:
     - Conteúdo =>
       . Propósito: // A preencher 
       . Qualidade: // A preencher 
     - Design => 
       . imagens: // A preencher 
       . color: white
       . background-color: // A preencher
       . background-images: // A preencher
       . media-queries: // A preencher
       . Tamanho do elementos: // A preencher
    - Tipografia
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       . text-decoration: // A preencher 
       
  b. Main:
  
   b.1. Seção Conta Virtual:
      - Conteúdo =>
       . Propósito: // A preencher 
       . Qualidade: // A preencher 
      - Design => 
       . imagens: // A preencher 
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . media-queries: // A preencher 
       . Tamanho do elementos: // A preencher
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
   
   b.2. Seção vantages e oferta da Conta Virtual:
      - Conteúdo =>
       . Propósito: // A preencher 
       . Qualidade: // A preencher 
      - Design => 
       . color: white
       . background-color: // A preencher 
       . backgroun-image: // A preencher 
       . imagem: // A preencher 
       . media-queries: // A preencher 
       . Tamanho do elementos: // A preencher
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       . text-decoration:  // A preencher 
       
    c. Footer:
      - Conteúdo =>
       . Propósito:
       . Qualidade:
      - Design =>
       . logo: / A preencher 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  5.1 Análise e sugestões:
  
    a. Análise: 
    - Funcionalidade: Não encontrei nenhum bug que impedisse a página de funcionar como deveria.
    - Responsividade: Nada a declarar.
     
    b. Sugestões: 

    - Apenas sugiro na parte de vantages, tirar os links dos butões para não ficarem enviando para a mesma página. Acredito que seja um comportamento desnecessário.

## 6.  Página de Login e Cadastre-se  

   a. Main:
  
    a.1. Forms:
      - Design => 
       . color: white
       . Tamanho do elementos: // A preencher
 
       
    b. Footer:
      - Design =>
       . logo: / A preencher 
       . color: white
       . background-color: // A preencher 
       . Tamanho do elementos: // A preencher
       . media-queries: // A preencher 
      - Tipografia =>
       . font-style: // A preencher 
       . font-family: // A preencher 
       . font-size: // A preencher 
       . font-weight: // A preencher 
       
  6.1 Análise e sugestões:
     
   a. Análise: 
    - Funcionalidade: Não encontrei nenhum bug que impedisse a página de funcionar como deveria.
    - Responsividade: Nada a declarar.

**Comment by sibelius** [comment]
tks, we gonna go in another direction
